# Generated by Django 5.0.1 on 2024-03-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_picture', models.FileField(upload_to='')),
                ('date_of_birth', models.DateField()),
                ('skills', models.CharField(max_length=120)),
                ('education', models.CharField(max_length=100)),
            ],
        ),
    ]
